version: '3.8'

volumes:
  source-deployments:
    external: true

services:
  app:
    build:
      dockerfile: Dockerfile
      context: react-app
      target: production
    volumes:
      - ./react-app:/var/src/react-app
      - /var/src/react-app/node_modules
    restart: always
    hostname: application
    env_file:
      - .env
    ports:
      - 8000:8000
      - 4444:80
    networks:
      - backend
      - frontend
  gateway:
    build:
      dockerfile: Dockerfile
      context: gateway
      target: production
    volumes:
      - ./gateway:/var/src/gateway
      - /var/src/gateway/node_modules
    command: npm run start
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
  deployment:
    build:
      dockerfile: Dockerfile
      context: deployment
      target: production
    volumes:
      - ./deployment:/var/src/deployment
      - /var/src/deployment/node_modules
      - /data
      - source-deployments:/var/www/source-deployments
    command: npm run start:debug
    restart: always
    hostname: deployment
    env_file:
      - .env
    networks:
      - backend
  project:
    build:
      dockerfile: Dockerfile
      context: project
      target: production
    volumes:
      - ./project:/var/src/project
      - /var/src/project/node_modules
    command: npm run start:debug
    restart: always
    hostname: project
    env_file:
      - .env
    networks:
      - backend
  storage:
    build:
      dockerfile: Dockerfile
      context: storage
      target: production
    volumes:
      - ./storage:/var/src/storage
      - /var/src/storage/node_modules
      - /data
    command: npm run start:debug
    restart: always
    hostname: storage
    env_file:
      - .env
    networks:
      - backend
  team:
    build:
      dockerfile: Dockerfile
      context: team
      target: production
    volumes:
      - ./team:/var/src/team
      - /var/src/team/node_modules
    command: npm run start:debug
    restart: always
    hostname: team
    env_file:
      - .env
    networks:
      - backend
  db:
    image: 'mongo:3.7'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
  nginx:
    image: nginx
    # build:
    #   dockerfile: Dockerfile
    #   context: nginx
    #   target: production
    restart: always
    hostname: nginx_manager
    # command: npm run start:debug
    env_file:
      - .env
    volumes:
      - source-deployments:/var/www/source-deployments
      # - ./nginx:/var/src/nginx
      # - /var/src/nginx/node_modules
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/config/error_page:/var/www/nginx/error_page:ro
    ports:
      - 80:80
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    restart: always
    hostname: redis_server
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes: 
      # - cache:/data
    networks:
    - backend

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure