version: '3.8'

volumes:
  bare_repositories:
    external: true
  builds:
    external: true
  # nginx-sites-enabled:
  #   external: true

services:
  app:
    build:
      dockerfile: Dockerfile
      context: react-app
      target: development
    volumes:
      - ./react-app:/var/src/react-app
      - /var/src/react-app/node_modules
    command: npm run start
    restart: always
    hostname: application
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend
  gateway:
    build:
      dockerfile: Dockerfile
      context: gateway
      target: development
    volumes:
      - ./gateway:/var/src/gateway
      - /var/src/gateway/node_modules
      - ./gateway/config/.gitconfig:/root/.gitconfig
    command: npm run start:debug
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
  deployment:
    build:
      dockerfile: Dockerfile
      context: deployment
      target: development
    volumes:
      - ./deployment:/var/src/deployment
      - /var/src/deployment/node_modules
      - bare_repositories:/var/www/bare_repositories
      - builds:/var/www/builds
      - ./deployment/config/.gitconfig:/root/.gitconfig
    command: npm run start:debug
    restart: always
    hostname: deployment
    env_file:
      - .env
    networks:
      - backend
  db:
    image: 'mongo:3.7'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
  caddy:
    build:
      dockerfile: Dockerfile
      context: caddy
      target: development
    restart: always
    hostname: caddy_server
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/src/caddy
      - /var/src/caddy/node_modules
      - builds:/var/www/builds
    # command: npm run start:debug
    networks:
      - backend
      - frontend

  api:
    build:
      dockerfile: Dockerfile
      context: api
      target: development
    volumes:
      - ./api:/var/src/api
      - /var/src/api/node_modules
    command: npm run start:debug
    restart: always
    hostname: api
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
  
  building:
    build:
      dockerfile: Dockerfile
      context: deployment
      target: development
    volumes:
      - ./deployment:/var/src/deployment
      - /var/src/deployment/node_modules
    command: npm run start:debug
    restart: always
    hostname: deployment
    env_file:
      - .env
    networks:
      - backend
      - frontend
  
  redis:
    image: redis:6.2-alpine
    restart: always
    hostname: redis_server
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes: 
      # - cache:/data
    networks:
    - backend
  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://localhost:4444/
    restart: always
    hostname: git_server
    networks:
      - backend
      - frontend
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4444:3000"
  
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: mysql_server
    environment:
      MYSQL_DATABASE: 'gitea'   
      MYSQL_USER: 'duong'
      MYSQL_PASSWORD: '123456'      
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    networks:
      - backend
      - frontend
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure